### ISSUE TITLE
AttributeError: 'TTS' object has no attribute 'speakers'

### ISSUE THREAD

**Issue by suoko** [FoamoftheSea/lingonaut-python#1]
Any idea about this error?

```
 python lingonaut.py
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
                                                                                                                                                      
...
Welcome to LingoNaut! How can I assist you in your learning journey today?
Traceback (most recent call last):
  File "/home/g/dev/lingonaut-python/lingonaut.py", line 294, in <module>
    main()
  File "/home/g/dev/lingonaut-python/lingonaut.py", line 255, in main
    play_audio(dump_to_audio(welcome_string, input_path))
  File "/home/g/dev/lingonaut-python/lingonaut.py", line 170, in dump_to_audio
    speaker=tts.speakers[10],
  File "/home/g/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TTS' object has no attribute 'speakers'
```

**Comment by webbrain-dev** [comment]
Hi! I opened a pull request (#2) to fix this. It resolves the `AttributeError: 'TTS' object has no attribute 'speakers'` by handling speaker selection more safely instead of assuming `tts.speakers` is available.

**Comment by FoamoftheSea** [comment]
@suoko Apologies that I did not see your issue sooner, I was completely distracted in March '24 by starting a new job position. The reason that you hit this issue is that you didn't install via the conda environment, which would have installed my personal fork of the `TTS` repo that contained bug fixes needed for compatibility. Hard-coding speaker selection as suggested in #2 works around this, but note that you would still need to install the forked `TTS` listed in `environment.yaml` in order to use this code, because otherwise you'll hit a different bug with an unsupported `verbose=False` flag that it uses. I have opened #5 to switch the upstream to a more modern version of TTS which doesn't require the use of my fork, but until that lands you'll need to do so.

@webbrain-dev Thank you for picking up on this, your activity on this thread helped me realize I missed it. I've reviewed your PR, but I had to request a change because using `"default"` is actually breaking according to my testing, so I've adopted your fix in spirit but instead hard-coded the name of the speaker I intended the user to get with the original `tts.speakers[10]`. Please accept the suggested change then we can merge.
